name: Continuous-Integration-Flow

on:
  pull_request:
    branches: [ "*" ]

jobs:
  run-ci-cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Say hello to the world of Continuous Integration
        run: |
          echo "Hello CI World!"
          echo "I am [TWOJE_IMIĘ] and I'm really glad this works"

